name: Send Organization Invite

on:
  issues:
    types: [opened]

jobs:
  Comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: dump Github context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
        
