name: Send Organization Invite

on:
  issues:
    types: [opened, reopened]

permissions:
  actions: write
  issues: write
  
jobs:
  invite-to-org:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dump Github context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash

      - name: Add Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for your interest in becoming a member in voninc :sparkles:
            An invitation has been sent to your account! Please check your [organization page][1]
            [1]: https://github.com/settings/organizations
      
