name: Send Organization Invite

on:
  issues:
    types: [opened]

jobs:
  invite-to-org:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Dump Github context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
